---
# vars file for ./roles/keepalived

keepalived_vip_interfaces:
  - { address: "{{ hostvars.app_v1e.ansible_host }}", device: 'enp0s8' }

keepalived_target: "{{ groups['apps'] }}"
keepalived_offset: 50
