---
# vars file for ./roles/keepalived

keepalived_vip_interfaces:
  - { address: "{{ hostvars.db_v1i.ansible_host }}", device: 'enp0s8' }
keepalived_target: "{{ groups['databases'] }}"
keepalived_offset: 20
