---
- name: Rolling Update for Nginx
  hosts: apps
  become: true
  serial: 1

  vars:
    cluster_service: app_cluster

  pre_tasks:
  - haproxy:
      state: disabled
      host: "{{ inventory_hostname }}"
      backend: "{{ cluster_service }}"
      socket: /var/run/haproxy.sock
      wait: yes
    delegate_to: "{{ item }}"
    with_items: "{{ groups.lbs }}"

  roles:
    - { role: nginx, tags: nginx}

  post_tasks:
  - haproxy:
      state: enabled
      host: "{{ inventory_hostname }}"
      backend: "{{ cluster_service }}"
      socket: /var/run/haproxy.sock
      wait: yes
    delegate_to: "{{ item }}"
    with_items: "{{ groups.lbs }}"
