---
- name: Download jenkis.war
  command: "wget -q -O /opt/tomcat/webapps/jenkins.war http://mirrors.jenkins.io/war-stable/latest/jenkins.war"
  args:
    creates: /opt/tomcat/webapps/jenkins.war
  notify: Restart tomcat

- name: Install ipa-gothic-fonts
  yum:
    name: "{{ item }}"
  with_items:
    - ipa-gothic-fonts

- name: Create fonts directory
  file:
    path: /opt/java/jre/lib/fonts/fallback
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Create symlink for ttf
  file:
    src: /usr/share/fonts/ipa-gothic/ipag.ttf
    dest: /opt/java/jre/lib/fonts/fallback/ipag.ttf
    state: link
  notify: Restart tomcat 
