- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true

#  vars:
#    ansible_sudo_pass: 'ansible'
#  environment:
#    http_proxy: "http://proxy.example.local:8080"
#    https_proxy: "http://proxy.example.local:8080"

  roles:
    - name: common/locale
      tags: locale
    - name: common/packages
      tags: packages
    - role: common/users
      tags: users
#    - name: common/networks
#      tags: net
    - name: common/resolver
      tags: resolver
    - role: common/times
      tags: time

  post_tasks:
    - name: Restart target nodes
      shell: >
             sleep 2 &&
             shutdown -r now "Ansible initialized"
      async: 5
      poll: 0
      ignore_errors: true

    - name: Waiting for server to come back
      local_action:
        module: wait_for
        host: "{{ ansible_host }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
