---
- name: Install Jenkins Server
  hosts: jenkins_servers
  become: true
  roles:
    - { role: common, tags: common }
    - { role: original/java, tags: java }
    - { role: original/tomcat, tags: tomcat }
    - { role: jenkins, tags: jenkins }

- name: Setup Jenkins Slaves
  hosts: jenkins_slaves
  become: true
  roles:
    - { role: common, tags: common }
    - { role: original/java, tags: java }
    - { role: jenkins-slave, tags: jenkins-slave }
