---
- name: Setup SpringWeb
  hosts: springweb_servers
  become: true
  roles:
    - { role: common, tags: common }
    - { role: java, tags: java }
    - { role: tomcat, tags: tomcat }
  tasks:
    - name: Set authorized key
      authorized_key:
        user: tomcat
        state: present
        key: "{{ lookup('file', './roles/jenkins/files/id_rsa.pub') }}"
